"""add name column to entities

Revision ID: 922b44e77c4f
Revises: 413d3e2e91af
Create Date: 2026-02-02 16:52:31.877314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '922b44e77c4f'
down_revision: Union[str, None] = '413d3e2e91af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.drop_column('case_entity_links', 'created_at')
    op.drop_column('document_similarities', 'created_at')
    op.add_column('documents', sa.Column('doc_type', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_entity_type_name'), 'entities', type_='unique')
    op.create_unique_constraint('uq_entity_type_normalized_name', 'entities', ['entity_type', 'normalized_name'])
    op.create_unique_constraint('uq_document_extraction', 'extractions', ['document_id'])
    op.drop_column('extractions', 'extracted_at')
    op.drop_column('features', 'created_at')
    op.drop_column('signals', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('features', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('extractions', sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_document_extraction', 'extractions', type_='unique')
    op.drop_constraint('uq_entity_type_normalized_name', 'entities', type_='unique')
    op.create_unique_constraint(op.f('uq_entity_type_name'), 'entities', ['entity_type', 'normalized_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'doc_type')
    op.add_column('document_similarities', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('case_entity_links', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    # ### end Alembic commands ###