"""add timestamps to features and signals

Revision ID: 99b91d6b076f
Revises: 922b44e77c4f
Create Date: 2026-02-02 18:47:59.379731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b91d6b076f'
down_revision: Union[str, None] = '922b44e77c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_entity_links', sa.Column('linked_at', sa.DateTime(), nullable=True))
    op.add_column('features', sa.Column('computed_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('detected_at', sa.DateTime(), nullable=True))
    op.alter_column('signals', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('signals', 'detected_at')
    op.drop_column('features', 'computed_at')
    op.drop_column('case_entity_links', 'linked_at')
    # ### end Alembic commands ###